import Link from "next/link";
import { AirVent, ArrowRight, BadgeCheck, Bolt, Building2, Check, Clock3, Droplets, MapPin, PhoneCall, ShieldCheck, Sparkles, ThermometerSun, Wrench } from "lucide-react";
import { QuoteForm } from "@/components/quote-form";

const services = [
  { icon: Bolt, number: "01", title: "Electrical", copy: "Fault finding, DB boards, plugs, lighting, installations and urgent electrical repairs.", points: ["Fault finding", "DB boards", "Lighting & plugs"] },
  { icon: AirVent, number: "02", title: "Air conditioning", copy: "Aircon installation, servicing, cleaning, gas refills and repairs for homes and businesses.", points: ["Installations", "Servicing", "Repairs & regassing"] },
  { icon: Wrench, number: "03", title: "Property maintenance", copy: "Geyser checks, minor plumbing, handyman work and the practical jobs that keep a property running.", points: ["Geyser checks", "Minor plumbing", "General upkeep"] },
];
const plans = [
  { name: "Essential", price: "From R500", cadence: "per month", items: ["Quarterly aircon filter clean", "Basic electrical inspection", "Priority booking"] },
  { name: "Property Care", price: "From R1,000", cadence: "per month", featured: true, items: ["Monthly aircon service", "Electrical and geyser checks", "Maintenance summary"] },
  { name: "Complete", price: "From R1,500", cadence: "per month", items: ["Monthly multi-service support", "Preventative inspections", "Priority call-outs"] },
];
function Brand() { return <span className="brand" aria-label="VoltAir Solutions"><img src="/voltair-logo.jpg" alt="VoltAir Solutions" /></span>; }

export default function Home() {
  return <main>
    <header className="site-header"><div className="shell nav-wrap"><Link href="#top" className="logo-link"><Brand /></Link><nav aria-label="Main navigation"><Link href="#services">Services</Link><Link href="#plans">Maintenance plans</Link><Link href="#about">Why VoltAir</Link></nav><Link className="button button-small" href="#quote">Request a quote <ArrowRight size={16} /></Link></div></header>
    <section id="top" className="hero"><div className="circuit circuit-a" /><div className="circuit circuit-b" /><div className="shell hero-grid"><div className="hero-copy"><p className="kicker"><span /> Electrical · HVAC · Maintenance</p><h1>One call.<br /><em>We fix it all.</em></h1><p className="hero-lead">Reliable property services for Johannesburg homeowners, landlords, property managers and businesses.</p><div className="hero-actions"><Link className="button button-lime" href="#quote">Get a quote <ArrowRight size={18} /></Link><Link className="text-link" href="#services">View our services <ArrowRight size={17} /></Link></div><div className="trust-row"><span><ShieldCheck size={18} /> Clear quotes</span><span><BadgeCheck size={18} /> Professional workmanship</span><span><Clock3 size={18} /> Fast response</span></div></div><aside className="diagnostic-card"><div className="diagnostic-top"><span className="live-dot" /> QUICK DIAGNOSIS</div><h2>What needs attention?</h2><div className="diagnostic-list"><Link href="#quote"><span className="service-symbol yellow"><Bolt size={22} /></span><span><b>Electrical fault</b><small>Trips, outages, plugs or lighting</small></span><ArrowRight size={18} /></Link><Link href="#quote"><span className="service-symbol cyan"><ThermometerSun size={22} /></span><span><b>Aircon trouble</b><small>Not cooling, leaking or noisy</small></span><ArrowRight size={18} /></Link><Link href="#quote"><span className="service-symbol green"><Droplets size={22} /></span><span><b>Maintenance job</b><small>Geyser, plumbing or general repairs</small></span><ArrowRight size={18} /></Link></div><p><PhoneCall size={16} /> Tell us what is wrong. We will confirm the next step.</p></aside></div></section>
    <section id="services" className="section services-section"><div className="shell"><div className="section-heading"><div><p className="kicker dark"><span /> What we do</p><h2>Practical services.<br />Properly handled.</h2></div><p>Three essential property services, managed through one reliable team. Less chasing. Fewer crossed wires.</p></div><div className="service-grid">{services.map(({ icon: Icon, number, title, copy, points }) => <article className="service-card" key={title}><div className="service-card-top"><span>{number}</span><Icon size={30} /></div><h3>{title}</h3><p>{copy}</p><ul>{points.map(point => <li key={point}><Check size={15} /> {point}</li>)}</ul><Link href="#quote">Ask about this service <ArrowRight size={16} /></Link></article>)}</div></div></section>
    <section id="about" className="section why-section"><div className="shell why-grid"><div className="why-visual"><div className="bolt-mark"><Sparkles size={66} /></div><div className="response-badge"><strong>FAST</strong><span>response<br />targeted</span></div></div><div><p className="kicker"><span /> Why VoltAir</p><h2>Maintenance without the scramble.</h2><p className="large-copy">You should not need three contractors and six follow-up calls to keep one property working.</p><div className="reason-list"><div><span>01</span><p><b>One point of contact</b><small>Electrical, aircon and general maintenance managed together.</small></p></div><div><span>02</span><p><b>Clear communication</b><small>Practical advice, transparent quoting and sensible next steps.</small></p></div><div><span>03</span><p><b>Work that stays tracked</b><small>Every enquiry is captured so nothing quietly disappears.</small></p></div></div></div></div></section>
    <section id="plans" className="section plans-section"><div className="shell"><div className="section-heading"><div><p className="kicker dark"><span /> Maintenance plans</p><h2>Look after it before<br />it lets you down.</h2></div><p>For homeowners, landlords and small businesses that prefer planned upkeep to expensive surprises.</p></div><div className="plan-grid">{plans.map(plan => <article className={`plan-card ${plan.featured ? "featured" : ""}`} key={plan.name}>{plan.featured && <span className="popular">Most practical</span>}<Building2 size={24} /><h3>{plan.name}</h3><p className="price">{plan.price}<small>{plan.cadence}</small></p><ul>{plan.items.map(item => <li key={item}><Check size={16} /> {item}</li>)}</ul><Link href="#quote" className={plan.featured ? "button button-lime" : "button button-outline"}>Enquire about this plan</Link></article>)}</div><p className="plan-note">Plan scope and final pricing depend on the property, equipment and service frequency.</p></div></section>
    <section id="quote" className="section quote-section"><div className="shell quote-grid"><div><p className="kicker"><span /> Request a quote</p><h2>Tell us what needs fixing.</h2><p>Give us the basics. VoltAir will use the details only to respond to your enquiry and plan the right service.</p><div className="quote-points"><span><BadgeCheck size={19} /> No vague sales pitch</span><span><Clock3 size={19} /> Quick follow-up</span><span><ShieldCheck size={19} /> Your details stay private</span></div></div><QuoteForm /></div></section>
    <footer><div className="shell footer-grid"><div><Brand /><p>Electrical, air conditioning and property maintenance across Johannesburg.</p></div><div><b>Services</b><Link href="#services">Electrical</Link><Link href="#services">Air conditioning</Link><Link href="#services">Property maintenance</Link></div><div><b>Next step</b><Link href="#quote">Request a quote</Link><Link href="#plans">Maintenance plans</Link></div></div><div className="shell footer-bottom"><span>© 2026 VoltAir Solutions</span><span>Johannesburg, South Africa</span></div></footer>
  </main>;
}
