"use client";
import { useState } from "react";
import { ArrowRight, CheckCircle2, LoaderCircle } from "lucide-react";
export function QuoteForm() {
  const [state, setState] = useState<"idle" | "sending" | "sent" | "error">("idle"); const [error, setError] = useState("");
  async function submit(formData: FormData) { setState("sending"); setError(""); const payload = Object.fromEntries(formData.entries()); try { const response = await fetch("/api/enquiries", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error || "Your enquiry could not be sent."); setState("sent"); } catch (err) { setError(err instanceof Error ? err.message : "Your enquiry could not be sent."); setState("error"); } }
  if (state === "sent") return <div className="quote-form success-panel"><CheckCircle2 size={46} /><h3>Enquiry received.</h3><p>Thank you. VoltAir has your details and can now follow up with the right next step.</p><button className="button button-outline" onClick={() => setState("idle")}>Send another enquiry</button></div>;
  return <form className="quote-form" action={submit}><div className="field-row"><label>Full name<input name="name" autoComplete="name" required placeholder="Your name" /></label><label>Phone or WhatsApp<input name="phone" autoComplete="tel" required placeholder="Your number" /></label></div><label>Email address<input name="email" type="email" autoComplete="email" required placeholder="you@example.com" /></label><div className="field-row"><label>Service<select name="service" required defaultValue=""><option value="" disabled>Select a service</option><option>Electrical</option><option>Air conditioning</option><option>Property maintenance</option><option>Maintenance plan</option></select></label><label>Suburb<input name="suburb" autoComplete="address-level2" placeholder="Your suburb" /></label></div><label>What needs attention?<textarea name="message" required rows={5} placeholder="Describe the problem, equipment or work needed" /></label><label className="consent"><input name="consent" type="checkbox" value="yes" required /><span>I consent to VoltAir using these details to respond to my enquiry.</span></label>{state === "error" && <p className="form-error" role="alert">{error}</p>}<button className="button button-lime form-submit" disabled={state === "sending"}>{state === "sending" ? <><LoaderCircle className="spin" size={18} /> Sending</> : <>Send enquiry <ArrowRight size={18} /></>}</button></form>;
}
